export * from './i18n/ru.i18n';
export * from './lib/configs/index';
export * from './lib/configs/projects.config';
export * from './lib/configs/statuses.config';
export * from './lib/configs/tasks.config';
export * from './lib/models/project';
export * from './lib/models/status-with-project';
export * from './lib/models/status';
export * from './lib/models/task';
