import { RuckenTodoCoreRuI18n } from './i18n/ru.i18n';
export { RuckenTodoCoreRuI18n } from './i18n/ru.i18n';
import { ChangesConfig } from './shared/configs/change.config';
export { ChangesConfig } from './shared/configs/change.config';
import { ProjectsConfig } from './shared/configs/project.config';
export { ProjectsConfig } from './shared/configs/project.config';
import { StatusesConfig } from './shared/configs/status.config';
export { StatusesConfig } from './shared/configs/status.config';
import { TasksConfig } from './shared/configs/task.config';
export { TasksConfig } from './shared/configs/task.config';
import { Change } from './shared/models/change';
export { Change } from './shared/models/change';
import { Project } from './shared/models/project';
export { Project } from './shared/models/project';
import { StatusWithProject } from './shared/models/status-with-project';
export { StatusWithProject } from './shared/models/status-with-project';
import { Status } from './shared/models/status';
export { Status } from './shared/models/status';
import { Task } from './shared/models/task';
export { Task } from './shared/models/task';
export const RuckenTodoCoreShareds: any[] = [RuckenTodoCoreRuI18n, Change, Project, StatusWithProject, Status, Task];
export const RuckenTodoCoreConfigs: any[] = [ChangesConfig, ProjectsConfig, StatusesConfig, TasksConfig];
